name: Adguard
services:
  Adguard:
    image: adguard/adguardhome:v0.107.73@sha256:7fbf01d73ecb7a32d2d9e6cef8bf88e64bd787889ca80a1e8bce30cd4c084442
    container_name: Adguard
    restart: unless-stopped
    hostname: adguard
    ports:
      - 53:53/tcp
      - 53:53/udp
    networks:
      - Adguard
    volumes:
      - adguard_work:/opt/adguardhome/work
      - ${DOCKER_VOLUMES}/Adguard:/opt/adguardhome/conf

    user: "${UID}:${GID}"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE

    logging:
      driver: "journald"
    healthcheck:
      test: ["CMD-SHELL", "netstat -tuln | grep ':53 ' >/dev/null || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          cpus: 0.25
          memory: 128M
          pids: 20

# Assumes you have already created a Docker Network called 'Adguard' (ex 'docker network create Adguard'). See the README for more information.
networks:
  Adguard:
    name: Adguard
    external: true

volumes:
  adguard_work:
